/**
 * Identifiers.
 *
 * Three kinds, for three audiences:
 *
 *   EntityId     opaque, unique, never shown to a customer
 *   OrderNumber  human, spoken aloud on the phone, printed on a box
 *   ViewToken    unguessable, handed to one customer, proves nothing else
 *
 * Note the mongodb driver is deliberately NOT imported here — the boundary check
 * forbids it outside infrastructure. Ids are generated by the domain and stored
 * as strings, so a document's identity never depends on the database that
 * happens to hold it.
 */

declare const idBrand: unique symbol;

/** A branded id. `EntityId<'Product'>` cannot be passed where `EntityId<'Order'>` is expected. */
export type EntityId<T extends string> = string & { readonly [idBrand]?: T };

export interface IdGenerator {
  /** A fresh, lexicographically sortable id. */
  next<T extends string>(): EntityId<T>;
}

const CROCKFORD = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';

const encodeBase32 = (value: number, length: number): string => {
  let out = '';
  let n = value;
  for (let i = 0; i < length; i++) {
    out = CROCKFORD.charAt(n % 32) + out;
    n = Math.floor(n / 32);
  }
  return out;
};

/**
 * ULID-shaped: 10 chars of millisecond timestamp + 16 chars of randomness.
 *
 * Sortable by creation time, which means the default index on _id is also a
 * chronological index — an admin listing "newest orders first" needs no extra
 * index, and no COLLSCAN. A random UUID would forfeit that.
 */
export const createIdGenerator = (now: () => number = Date.now): IdGenerator => ({
  next: <T extends string>(): EntityId<T> => {
    const time = encodeBase32(now(), 10);
    const bytes = new Uint8Array(16);
    globalThis.crypto.getRandomValues(bytes);
    let random = '';
    for (const b of bytes) random += CROCKFORD.charAt(b % 32);
    return (time + random) as EntityId<T>;
  },
});

/** True for a well-formed id produced by createIdGenerator. */
export const isEntityId = (value: unknown): value is EntityId<string> =>
  typeof value === 'string' && /^[0-9A-HJKMNP-TV-Z]{26}$/.test(value);

/** How many Crockford characters a view token carries. 26 × 5 bits = 130. */
const VIEW_TOKEN_LENGTH = 26;

/**
 * An unguessable string to put in a URL somebody is allowed to open.
 *
 * NOT `createIdGenerator`, deliberately, even though the alphabet and length
 * match. An id is sortable BECAUSE its first ten characters are the clock, and
 * a token whose first ten characters are the clock is a token where an attacker
 * who knows roughly when an order was placed has ten fewer characters to guess.
 * Every character here is from the CSPRNG.
 *
 * 130 bits. The thing it protects is a name, a phone number and a street
 * address, and it travels in a URL that gets pasted into WhatsApp — so it is
 * sized to be pointless to attack rather than merely inconvenient.
 *
 * `% 32` is uniform here and would not be for an alphabet that did not divide
 * 256: Crockford is exactly 32 characters, so each maps to exactly 8 byte
 * values.
 */
export const createViewToken = (): string => {
  const bytes = new Uint8Array(VIEW_TOKEN_LENGTH);
  globalThis.crypto.getRandomValues(bytes);
  let token = '';
  for (const byte of bytes) token += CROCKFORD.charAt(byte % 32);
  return token;
};

/** True for a well-formed view token. Shape only — it says nothing about validity. */
export const isViewToken = (value: unknown): value is string =>
  typeof value === 'string' && /^[0-9A-HJKMNP-TV-Z]{26}$/.test(value);

/**
 * Human order number: T4T-26-000042.
 *
 * The sequence comes from infrastructure (an atomic counter); this only decides
 * the shape. Padded to six digits so it stays fixed-width on an invoice, and
 * carries the two-digit year so the sequence can reset annually without
 * colliding with last year's numbers.
 */
export const formatOrderNumber = (year: number, sequence: number): string =>
  `T4T-${String(year % 100).padStart(2, '0')}-${String(sequence).padStart(6, '0')}`;

export const parseOrderNumber = (value: string): { year: number; sequence: number } | null => {
  const m = /^T4T-(\d{2})-(\d{6})$/.exec(value.trim().toUpperCase());
  if (m === null) return null;
  return { year: 2000 + Number(m[1]), sequence: Number(m[2]) };
};
