/**
 * Identifiers.
 *
 * Two kinds, for two audiences:
 *
 *   EntityId   opaque, unique, never shown to a customer
 *   OrderNumber  human, spoken aloud on the phone, printed on a box
 *
 * Note the mongodb driver is deliberately NOT imported here — the boundary check
 * forbids it outside infrastructure. Ids are generated by the domain and stored
 * as strings, so a document's identity never depends on the database that
 * happens to hold it.
 */

declare const idBrand: unique symbol;

/** A branded id. `EntityId<'Product'>` cannot be passed where `EntityId<'Order'>` is expected. */
export type EntityId<T extends string> = string & { readonly [idBrand]?: T };

export interface IdGenerator {
  /** A fresh, lexicographically sortable id. */
  next<T extends string>(): EntityId<T>;
}

const CROCKFORD = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';

const encodeBase32 = (value: number, length: number): string => {
  let out = '';
  let n = value;
  for (let i = 0; i < length; i++) {
    out = CROCKFORD.charAt(n % 32) + out;
    n = Math.floor(n / 32);
  }
  return out;
};

/**
 * ULID-shaped: 10 chars of millisecond timestamp + 16 chars of randomness.
 *
 * Sortable by creation time, which means the default index on _id is also a
 * chronological index — an admin listing "newest orders first" needs no extra
 * index, and no COLLSCAN. A random UUID would forfeit that.
 */
export const createIdGenerator = (now: () => number = Date.now): IdGenerator => ({
  next: <T extends string>(): EntityId<T> => {
    const time = encodeBase32(now(), 10);
    const bytes = new Uint8Array(16);
    globalThis.crypto.getRandomValues(bytes);
    let random = '';
    for (const b of bytes) random += CROCKFORD.charAt(b % 32);
    return (time + random) as EntityId<T>;
  },
});

/** True for a well-formed id produced by createIdGenerator. */
export const isEntityId = (value: unknown): value is EntityId<string> =>
  typeof value === 'string' && /^[0-9A-HJKMNP-TV-Z]{26}$/.test(value);

/**
 * Human order number: T4T-26-000042.
 *
 * The sequence comes from infrastructure (an atomic counter); this only decides
 * the shape. Padded to six digits so it stays fixed-width on an invoice, and
 * carries the two-digit year so the sequence can reset annually without
 * colliding with last year's numbers.
 */
export const formatOrderNumber = (year: number, sequence: number): string =>
  `T4T-${String(year % 100).padStart(2, '0')}-${String(sequence).padStart(6, '0')}`;

export const parseOrderNumber = (value: string): { year: number; sequence: number } | null => {
  const m = /^T4T-(\d{2})-(\d{6})$/.exec(value.trim().toUpperCase());
  if (m === null) return null;
  return { year: 2000 + Number(m[1]), sequence: Number(m[2]) };
};
